### ISSUE TITLE
存在字符编码编码错误

### ISSUE THREAD

**Issue by niinaranpo** [hanFengSan/anime-sales#1]
![](http://i.imgur.com/2s9xe0h.png)

**Comment by hanFengSan** [comment]
get, 我找找解决方案, 主要是java从shift_jis解码的时候出现的乱码, 有点无奈= =

**Comment by niinaranpo** [comment]
@hanFengSan 
趁现在还能查先赶紧把前几天的日榜数据搞下来

**Comment by niinaranpo** [comment]
@hanFengSan 
趁还能查，先赶紧把前几天日榜数据搞下来比较好

**Comment by hanFengSan** [comment]
解决了, 具体原因:
>Shift_JIS 的文字集合基本是按照JIS X 0208规定的。但实际上各个厂商各自进行扩展，包含了大量重复的、规格以外的文字。因此，Windows在本来的 Shift_Jis的文字集合之外，又增加了NEC扩展、IBM扩展所包含的文字。这种规格和实际情况的分歧长期存在，随着windows-31J的规格 化，混乱情况有所改善。

坑爹的Shift_JIS的扩展字符.
